version: "3.9"

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: flowervision-backend

    restart: unless-stopped

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    volumes:
      - ./backend:/app
      - ./models:/app/models

    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

    networks:
      - flowervision-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: flowervision-frontend

    restart: unless-stopped

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    command: npm run dev -- --host

    depends_on:
      - backend

    networks:
      - flowervision-network

networks:
  flowervision-network:
    driver: bridge
